# Generated by Django 2.1.7 on 2019-04-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_auto_20190404_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
