# Generated by Django 2.1.7 on 2019-04-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_order_pos_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
    ]
