# Generated by Django 2.1.7 on 2019-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0007_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待上传'), (4, '待审核'), (5, '成功'), (4, '失败')], default=1),
        ),
    ]
