# Generated by Django 2.1.7 on 2019-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0008_auto_20190406_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
