# Generated by Django 2.1.7 on 2019-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0009_order_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.IntegerField(choices=[(2, '门店办理'), (1, '小程序')], default=1),
        ),
    ]
