# Generated by Django 2.1.7 on 2019-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0011_order_pay_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_method',
            field=models.IntegerField(choices=[(1, '小程序'), (2, '门店办理')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '待支付'), (2, '已支付'), (3, '待上传'), (4, '待审核'), (5, '成功'), (4, '失败')], default=0),
        ),
    ]
