# Generated by Django 2.1.7 on 2019-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0012_auto_20190407_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(default='泰国', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_method',
            field=models.IntegerField(choices=[(1, '门店办理'), (0, '小程序')], default=1),
        ),
    ]
